"""
V2 Executor for Template System V2.0 - Phase 7.

This module handles execution of prompts via SD WebUI API,
integrating with the existing V1 API client and output management.
"""

import base64
import json
from pathlib import Path
from typing import List, Dict, Any, Optional, Callable
from datetime import datetime

from rich.console import Console
from rich.panel import Panel

from api.sdapi_client import SDAPIClient, PromptConfig, GenerationConfig

console = Console()


class V2Executor:
    """
    Executes prompts generated by V2Pipeline via SD WebUI API.

    Responsibilities:
    - Execute prompts via SD API client
    - Save images to output directory
    - Save metadata JSON alongside images
    - Support batch processing with progress reporting
    - Handle API errors gracefully

    Example:
        executor = V2Executor(api_client, output_dir="~/output")
        results = executor.execute_prompts(
            prompts,
            batch_size=1,
            progress_callback=lambda i, total: print(f"{i}/{total}")
        )
    """

    def __init__(
        self,
        api_client: SDAPIClient = None,
        output_dir: str = None,
        session_name: str = None
    ):
        """
        Initialize the executor.

        Args:
            api_client: SD API client instance (creates default if None)
            output_dir: Output directory for images (default: ./output)
            session_name: Optional session name for organizing outputs
        """
        self.api_client = api_client or SDAPIClient()
        self.output_dir = Path(output_dir or "./output")
        self.session_name = session_name or datetime.now().strftime("%Y%m%d_%H%M%S")

        # Create output directory
        self.session_dir = self.output_dir / self.session_name
        self.session_dir.mkdir(parents=True, exist_ok=True)

    def execute_prompts(
        self,
        prompts: List[Dict[str, Any]],
        batch_size: int = 1,
        progress_callback: Optional[Callable[[int, int], None]] = None
    ) -> List[Dict[str, Any]]:
        """
        Execute all prompts and save images with metadata.

        Args:
            prompts: List of prompt dicts from V2Pipeline.generate()
            batch_size: Number of images per API call (default: 1)
            progress_callback: Optional callback(current, total) for progress

        Returns:
            List of result dicts with format:
            {
                'prompt': str,
                'negative_prompt': str,
                'seed': int,
                'variations': Dict[str, str],
                'parameters': Dict[str, Any],
                'image_path': Path,
                'metadata_path': Path,
                'success': bool,
                'error': Optional[str]
            }

        Note:
            batch_size is applied at API level (n_iter parameter).
            Each prompt is still executed separately for metadata tracking.
        """
        results = []
        total = len(prompts)

        for idx, prompt_dict in enumerate(prompts):
            # Progress callback
            if progress_callback:
                progress_callback(idx, total)

            # Execute single prompt
            result = self.execute_single(prompt_dict, image_number=idx + 1)
            results.append(result)

            # Stop on error if desired (currently continues)
            if not result['success']:
                print(f"Warning: Failed to generate image {idx + 1}: {result['error']}")

        # Final progress callback
        if progress_callback:
            progress_callback(total, total)

        return results

    def execute_single(
        self,
        prompt_dict: Dict[str, Any],
        image_number: int = 1
    ) -> Dict[str, Any]:
        """
        Execute a single prompt and save image with metadata.

        Args:
            prompt_dict: Prompt dict from V2Pipeline
            image_number: Image number for filename (1-based)

        Returns:
            Result dict with image_path, metadata_path, success, error
        """
        result = {
            **prompt_dict,
            'image_path': None,
            'metadata_path': None,
            'success': False,
            'error': None
        }

        try:
            # Build API prompt config
            api_prompt = PromptConfig(
                prompt=prompt_dict['prompt'],
                negative_prompt=prompt_dict.get('negative_prompt', ''),
                seed=prompt_dict.get('seed', -1),
                filename=f"image_{image_number:04d}"
            )

            # Apply parameters if present
            if 'parameters' in prompt_dict:
                self._apply_parameters(prompt_dict['parameters'])

            # Log the actual prompt being sent to API
            self._log_prompt(api_prompt, image_number)

            # Call SD API
            response = self.api_client.generate_image(api_prompt)

            # Save image
            image_path = self._save_image(
                response['images'][0],
                image_number
            )

            # Save metadata
            metadata_path = self._save_metadata(
                image_path,
                prompt_dict,
                response
            )

            result['image_path'] = image_path
            result['metadata_path'] = metadata_path
            result['success'] = True

        except Exception as e:
            result['error'] = str(e)

        return result

    def _apply_parameters(self, parameters: Dict[str, Any]):
        """
        Apply generation parameters to API client.

        Args:
            parameters: Parameters dict from prompt config
        """
        config = GenerationConfig()

        # Map parameters to GenerationConfig fields
        param_mapping = {
            'steps': 'steps',
            'cfg_scale': 'cfg_scale',
            'width': 'width',
            'height': 'height',
            'sampler': 'sampler_name',
            'scheduler': 'scheduler',
            'batch_size': 'batch_size',
            'n_iter': 'n_iter',
            'enable_hr': 'enable_hr',
            'hr_scale': 'hr_scale',
            'hr_upscaler': 'hr_upscaler',
            'denoising_strength': 'denoising_strength',
            'hr_second_pass_steps': 'hr_second_pass_steps'
        }

        for param_key, config_key in param_mapping.items():
            if param_key in parameters:
                setattr(config, config_key, parameters[param_key])

        self.api_client.set_generation_config(config)

    def _log_prompt(self, api_prompt: PromptConfig, image_number: int):
        """
        Log the actual prompt being sent to API.

        Args:
            api_prompt: PromptConfig being sent to API
            image_number: Image number for identification
        """
        # Build prompt display text
        prompt_text = f"[bold cyan]Prompt #{image_number}[/bold cyan]\n\n"
        prompt_text += f"[yellow]Positive:[/yellow]\n{api_prompt.prompt}\n\n"

        if api_prompt.negative_prompt:
            prompt_text += f"[red]Negative:[/red]\n{api_prompt.negative_prompt}\n\n"

        prompt_text += f"[green]Seed:[/green] {api_prompt.seed}"

        # Display in a panel
        console.print(Panel(
            prompt_text,
            title=f"[bold]API Request #{image_number}[/bold]",
            border_style="cyan",
            expand=False
        ))

    def _save_image(self, base64_data: str, image_number: int) -> Path:
        """
        Save base64 image data to file.

        Args:
            base64_data: Base64-encoded PNG image
            image_number: Image number for filename

        Returns:
            Path to saved image file
        """
        # Decode base64
        image_bytes = base64.b64decode(base64_data)

        # Generate filename
        filename = f"image_{image_number:04d}.png"
        image_path = self.session_dir / filename

        # Save file
        image_path.write_bytes(image_bytes)

        return image_path

    def _save_metadata(
        self,
        image_path: Path,
        prompt_dict: Dict[str, Any],
        api_response: Dict[str, Any]
    ) -> Path:
        """
        Save prompt metadata as JSON alongside image.

        Args:
            image_path: Path to saved image
            prompt_dict: Original prompt dict
            api_response: Raw API response

        Returns:
            Path to saved metadata JSON file
        """
        metadata = {
            'prompt': prompt_dict['prompt'],
            'negative_prompt': prompt_dict.get('negative_prompt', ''),
            'seed': prompt_dict.get('seed', -1),
            'variations': prompt_dict.get('variations', {}),
            'parameters': prompt_dict.get('parameters', {}),
            'image_path': str(image_path),
            'timestamp': datetime.now().isoformat(),
            'api_info': json.loads(api_response.get('info', '{}'))
        }

        # Save as JSON
        metadata_path = image_path.with_suffix('.json')
        metadata_path.write_text(
            json.dumps(metadata, indent=2, ensure_ascii=False),
            encoding='utf-8'
        )

        return metadata_path

    def set_output_dir(self, output_dir: str, session_name: str = None):
        """
        Change output directory and optionally session name.

        Args:
            output_dir: New output directory
            session_name: Optional new session name
        """
        self.output_dir = Path(output_dir)
        if session_name:
            self.session_name = session_name
        else:
            self.session_name = datetime.now().strftime("%Y%m%d_%H%M%S")

        self.session_dir = self.output_dir / self.session_name
        self.session_dir.mkdir(parents=True, exist_ok=True)

    def test_connection(self) -> bool:
        """
        Test connection to SD API.

        Returns:
            True if API is accessible, False otherwise
        """
        return self.api_client.test_connection()

    def get_session_summary(self, results: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Generate summary statistics for a batch execution.

        Args:
            results: Results from execute_prompts()

        Returns:
            Summary dict with success/failure counts, paths, etc.
        """
        successful = [r for r in results if r['success']]
        failed = [r for r in results if not r['success']]

        return {
            'total': len(results),
            'successful': len(successful),
            'failed': len(failed),
            'session_dir': str(self.session_dir),
            'image_paths': [str(r['image_path']) for r in successful],
            'errors': [
                {'index': idx, 'error': r['error']}
                for idx, r in enumerate(results)
                if not r['success']
            ]
        }
