"""Service for extracting metadata from SD-generated PNG images."""

import re
from pathlib import Path
from typing import Any, Optional

from PIL import Image


def extract_png_metadata(image_path: str | Path) -> dict[str, Any]:
    """
    Extract metadata from PNG image generated by Stable Diffusion WebUI.

    Reads the 'parameters' chunk from PNG metadata which contains:
    - Full prompt
    - Negative prompt
    - Generation parameters (seed, steps, cfg_scale, sampler, etc.)

    Args:
        image_path: Path to PNG image file

    Returns:
        Dictionary containing parsed metadata

    Raises:
        FileNotFoundError: If image does not exist
        ValueError: If image has no metadata or invalid format
    """
    image_path = Path(image_path)

    if not image_path.exists():
        raise FileNotFoundError(f"Image not found: {image_path}")

    # Open image and read PNG info
    try:
        with Image.open(image_path) as img:
            # Get 'parameters' chunk (SD WebUI standard)
            parameters = img.info.get('parameters', '')
    except Exception as e:
        raise ValueError(f"Failed to read image: {e}") from e

    if not parameters:
        raise ValueError("Image has no metadata (missing 'parameters' chunk)")

    # Parse SD WebUI metadata format:
    # Line 0: Prompt
    # Line 1: Negative prompt: ...
    # Line 2: Steps: X, Sampler: Y, ...
    lines = parameters.split('\n')

    # Extract prompt (line 0)
    prompt = lines[0] if len(lines) > 0 else ''

    # Extract negative prompt (line 1)
    negative_prompt = ''
    if len(lines) > 1 and lines[1].startswith('Negative prompt:'):
        negative_prompt = lines[1].replace('Negative prompt:', '').strip()

    # Extract parameters (line 2)
    params_dict: dict[str, Any] = {}
    if len(lines) > 2:
        param_line = lines[2]

        # Parse format: "Key: Value, Key2: Value2, ..."
        # Using regex to handle commas inside values
        for match in re.finditer(r'(\w[\w\s]*?):\s*([^,]+?)(?:,\s*(?=\w)|$)', param_line):
            key = match.group(1).strip()
            value = match.group(2).strip()
            params_dict[key] = value

    # Build structured metadata
    metadata = {
        'prompt': prompt,
        'negative_prompt': negative_prompt,
        'seed': _parse_int(params_dict.get('Seed'), -1),
        'steps': _parse_int(params_dict.get('Steps'), 20),
        'sampler': params_dict.get('Sampler', ''),
        'scheduler': params_dict.get('Schedule type', ''),
        'cfg_scale': _parse_float(params_dict.get('CFG scale'), 7.0),
        'size': params_dict.get('Size', ''),
        'model': params_dict.get('Model', ''),
        'model_hash': params_dict.get('Model hash', ''),
        'clip_skip': _parse_int(params_dict.get('Clip skip')),
        'denoising_strength': _parse_float(params_dict.get('Denoising strength')),
        'hires_upscaler': params_dict.get('Hires upscaler'),
        'hires_steps': _parse_int(params_dict.get('Hires steps')),
        'hires_resize': params_dict.get('Hires resize'),
        'version': params_dict.get('Version'),
        # Store all params for additional access
        'all_params': params_dict,
        # Store raw for debugging
        'raw_parameters': parameters,
    }

    # Parse size into width/height
    if metadata['size']:
        size_parts = metadata['size'].split('x')
        if len(size_parts) == 2:
            metadata['width'] = _parse_int(size_parts[0])
            metadata['height'] = _parse_int(size_parts[1])

    return metadata


def _parse_int(value: Optional[str], default: Optional[int] = None) -> Optional[int]:
    """Parse integer from string, return default if invalid."""
    if value is None:
        return default
    try:
        return int(float(value))  # Handle "42.0" format
    except (ValueError, TypeError):
        return default


def _parse_float(value: Optional[str], default: Optional[float] = None) -> Optional[float]:
    """Parse float from string, return default if invalid."""
    if value is None:
        return default
    try:
        return float(value)
    except (ValueError, TypeError):
        return default
